import type { Profile } from '@/types/api/profile'

const hoursAgo = (h: number) => new Date(Date.now() - h * 3600000).toISOString()

export const MOCK_PROFILES: Profile[] = [
  {
    id: 'prof-001',
    job_id: 'job-001-summer-skincare',
    username: 'theglowdiary',
    full_name: 'The Glow Diary',
    bio: 'Clean beauty advocate. Sharing my skincare journey, honest reviews, and glow-up tips. Collab: hello@theglowdiary.com',
    profile_pic_url: 'https://i.pravatar.cc/150?u=theglowdiary',
    follower_count: 128000,
    following_count: 1200,
    post_count: 845,
    engagement_rate: 6.2,
    email: 'hello@theglowdiary.com',
    email_source: 'bio',
    website: 'https://theglowdiary.com',
    status: 'done',
    is_bookmarked: true,
    score: {
      overall_score: 94,
      engagement: 92,
      relevance: 96,
      authenticity: 90,
      reach: 88,
      content_quality: 95,
      brand_alignment: 97,
      reasoning: 'Exceptional brand alignment with clean beauty focus. Verified high engagement rate of 6.2%. Content quality is outstanding with consistent aesthetic. Perfect candidate for skincare collaborations.',
    },
    created_at: hoursAgo(48),
  },
  {
    id: 'prof-002',
    job_id: 'job-001-summer-skincare',
    username: 'skincarebysomi',
    full_name: 'Somi Kim',
    bio: 'Esthetician & skincare educator. Korean beauty meets western science. DM for collabs.',
    profile_pic_url: 'https://i.pravatar.cc/150?u=skincarebysomi',
    follower_count: 45200,
    following_count: 890,
    post_count: 312,
    engagement_rate: 4.8,
    email: 'somi@skincarebysomi.com',
    email_source: 'website_scrape',
    website: 'https://skincarebysomi.com',
    status: 'done',
    is_bookmarked: true,
    score: {
      overall_score: 82,
      engagement: 85,
      relevance: 80,
      authenticity: 88,
      reach: 72,
      content_quality: 84,
      brand_alignment: 82,
      reasoning: 'Strong engagement rate with authentic following. K-beauty expertise aligns well with skincare brands. Smaller reach but highly engaged niche audience.',
    },
    created_at: hoursAgo(47),
  },
  {
    id: 'prof-003',
    job_id: 'job-001-summer-skincare',
    username: 'naturallyradiant',
    full_name: 'Priya Sharma',
    bio: 'Ayurvedic skincare meets modern beauty. Plant-based skincare routines for South Asian skin.',
    profile_pic_url: 'https://i.pravatar.cc/150?u=naturallyradiant',
    follower_count: 67800,
    following_count: 1450,
    post_count: 523,
    engagement_rate: 5.1,
    email: 'priya@naturallyradiant.in',
    email_source: 'website_scrape',
    phone: '+91-98765-43210',
    website: 'https://naturallyradiant.in',
    address: 'Mumbai, India',
    status: 'done',
    is_bookmarked: false,
    score: {
      overall_score: 78,
      engagement: 80,
      relevance: 75,
      authenticity: 82,
      reach: 76,
      content_quality: 78,
      brand_alignment: 74,
      reasoning: 'Good engagement and authentic audience in the beauty niche. Ayurvedic focus provides unique positioning. Strong in South Asian market which could expand brand reach.',
    },
    created_at: hoursAgo(46),
  },
  {
    id: 'prof-004',
    job_id: 'job-001-summer-skincare',
    username: 'dewyskinco',
    full_name: 'Dewy Skin Co.',
    bio: 'Minimalist skincare routines that actually work. Less is more.',
    profile_pic_url: 'https://i.pravatar.cc/150?u=dewyskinco',
    follower_count: 32100,
    following_count: 445,
    post_count: 198,
    engagement_rate: 3.4,
    email: 'hello@dewyskin.co',
    email_source: 'llm_extraction',
    status: 'done',
    is_bookmarked: false,
    score: {
      overall_score: 68,
      engagement: 65,
      relevance: 72,
      authenticity: 70,
      reach: 62,
      content_quality: 68,
      brand_alignment: 71,
      reasoning: 'Decent engagement for minimalist skincare niche. Smaller audience but well-targeted. Content style aligns with clean beauty aesthetic but posting frequency could be higher.',
    },
    created_at: hoursAgo(45),
  },
  {
    id: 'prof-005',
    job_id: 'job-001-summer-skincare',
    username: 'beautybyella',
    full_name: 'Ella Rodriguez',
    bio: 'Beauty content creator. Makeup tutorials, skincare reviews, GRWM. Business: ella@beautybiz.com',
    profile_pic_url: 'https://i.pravatar.cc/150?u=beautybyella',
    follower_count: 215000,
    following_count: 980,
    post_count: 1230,
    engagement_rate: 2.8,
    email: 'ella@beautybiz.com',
    email_source: 'bio',
    website: 'https://beautybyella.com',
    status: 'done',
    is_bookmarked: false,
    score: {
      overall_score: 62,
      engagement: 55,
      relevance: 60,
      authenticity: 65,
      reach: 85,
      content_quality: 62,
      brand_alignment: 52,
      reasoning: 'High reach but lower engagement rate for the follower count. Content is more makeup-focused than skincare, which reduces brand alignment. Could work for broader beauty campaigns.',
    },
    created_at: hoursAgo(44),
  },
  {
    id: 'prof-006',
    job_id: 'job-001-summer-skincare',
    username: 'glowgetterjen',
    full_name: 'Jennifer Wu',
    bio: 'Skincare obsessed. Product junkie. Sharing what works (and what doesn\'t).',
    profile_pic_url: 'https://i.pravatar.cc/150?u=glowgetterjen',
    follower_count: 18500,
    following_count: 2100,
    post_count: 89,
    engagement_rate: 8.7,
    status: 'done',
    is_bookmarked: false,
    score: {
      overall_score: 55,
      engagement: 90,
      relevance: 70,
      authenticity: 45,
      reach: 35,
      content_quality: 50,
      brand_alignment: 55,
      reasoning: 'Exceptionally high engagement but very small audience. High following-to-follower ratio raises authenticity concerns. Content is relevant but inconsistent in quality and posting schedule.',
    },
    created_at: hoursAgo(43),
  },
  {
    id: 'prof-007',
    job_id: 'job-001-summer-skincare',
    username: 'dermskinexpert',
    full_name: 'Dr. Aisha Patel',
    bio: 'Board-certified dermatologist. Evidence-based skincare education.',
    profile_pic_url: 'https://i.pravatar.cc/150?u=dermskinexpert',
    follower_count: 89300,
    following_count: 340,
    post_count: 567,
    engagement_rate: 3.9,
    status: 'processing',
    is_bookmarked: false,
    created_at: hoursAgo(42),
  },
  {
    id: 'prof-008',
    job_id: 'job-001-summer-skincare',
    username: 'cleanbeautycollective',
    full_name: 'Clean Beauty Collective',
    bio: 'Curating the best in clean, non-toxic beauty. Feature submissions open.',
    profile_pic_url: 'https://i.pravatar.cc/150?u=cleanbeautycollective',
    follower_count: 156000,
    following_count: 890,
    post_count: 1450,
    engagement_rate: 2.1,
    status: 'processing',
    is_bookmarked: false,
    created_at: hoursAgo(41),
  },
  {
    id: 'prof-009',
    job_id: 'job-001-summer-skincare',
    username: 'skinfluencermark',
    full_name: 'Mark Thompson',
    bio: 'Male skincare advocate. Breaking the stigma. Routine builder.',
    profile_pic_url: 'https://i.pravatar.cc/150?u=skinfluencermark',
    follower_count: 28700,
    following_count: 1800,
    post_count: 145,
    engagement_rate: 1.2,
    status: 'new',
    is_bookmarked: false,
    created_at: hoursAgo(40),
  },
]
