import type { Job } from '@/types/api/job'

const now = new Date()
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000).toISOString()
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString()

export const MOCK_JOBS: Job[] = [
  {
    id: 'job-001-summer-skincare',
    user_id: 'mock-user-001',
    name: 'Summer 2026 Skincare Campaign',
    status: 'completed',
    brand_description: 'Premium organic skincare brand targeting Gen Z and millennials who value clean beauty, sustainability, and minimalist aesthetics.',
    reference_profiles: [
      'https://instagram.com/glossier',
      'https://instagram.com/tatcha',
      'https://instagram.com/drunk_elephant',
    ],
    follower_range_min: 10000,
    follower_range_max: 500000,
    discovery_limit: 50,
    keywords: ['skincare', 'clean beauty', 'organic', 'glow'],
    hashtags: ['#skincare', '#cleanbeauty', '#glowup', '#selfcare'],
    min_score_threshold: 60,
    target_country: 'US',
    profiles_discovered: 48,
    profiles_scored: 45,
    created_at: daysAgo(3),
    updated_at: daysAgo(3),
  },
  {
    id: 'job-002-fitness-collab',
    user_id: 'mock-user-001',
    name: 'Fitness Brand Collab Q3',
    status: 'scoring',
    brand_description: 'High-performance fitness apparel brand focused on CrossFit, HIIT, and functional training communities.',
    reference_profiles: [
      'https://instagram.com/gymshark',
      'https://instagram.com/nike',
    ],
    follower_range_min: 5000,
    follower_range_max: 200000,
    discovery_limit: 30,
    keywords: ['fitness', 'workout', 'gym', 'HIIT'],
    hashtags: ['#fitfam', '#gymlife', '#workout'],
    min_score_threshold: 50,
    profiles_discovered: 35,
    profiles_scored: 22,
    created_at: daysAgo(1),
    updated_at: hoursAgo(2),
  },
  {
    id: 'job-003-organic-food',
    user_id: 'mock-user-001',
    name: 'Organic Food Partners',
    status: 'discovering',
    brand_description: 'Farm-to-table organic food delivery service targeting health-conscious families in urban areas.',
    reference_profiles: [
      'https://instagram.com/dailyharvest',
      'https://instagram.com/hungryroot',
    ],
    follower_range_min: 2000,
    follower_range_max: 100000,
    discovery_limit: 25,
    keywords: ['organic', 'healthy eating', 'meal prep'],
    hashtags: ['#organicfood', '#healthyeating', '#mealprep'],
    min_score_threshold: 55,
    profiles_discovered: 18,
    profiles_scored: 0,
    created_at: hoursAgo(2),
    updated_at: hoursAgo(1),
  },
  {
    id: 'job-004-tech-accessories',
    user_id: 'mock-user-001',
    name: 'Tech Accessories Launch',
    status: 'failed',
    brand_description: 'Premium phone cases and tech accessories brand with minimalist design aesthetic.',
    reference_profiles: [
      'https://instagram.com/casetify',
      'https://instagram.com/dbrand',
    ],
    follower_range_min: 10000,
    follower_range_max: 300000,
    discovery_limit: 20,
    keywords: ['tech', 'accessories', 'minimalist'],
    hashtags: ['#techstyle', '#phonecase'],
    min_score_threshold: 60,
    profiles_discovered: 12,
    profiles_scored: 8,
    error_message: 'Apify rate limit exceeded. Please retry after a few minutes.',
    created_at: daysAgo(5),
    updated_at: daysAgo(5),
  },
  {
    id: 'job-005-sustainable-fashion',
    user_id: 'mock-user-001',
    name: 'Sustainable Fashion Q4',
    status: 'pending',
    brand_description: 'Eco-friendly fashion brand using recycled materials and ethical manufacturing.',
    reference_profiles: [
      'https://instagram.com/reformation',
      'https://instagram.com/everlane',
    ],
    follower_range_min: 5000,
    follower_range_max: 250000,
    discovery_limit: 40,
    keywords: ['sustainable', 'ethical fashion', 'eco-friendly'],
    hashtags: ['#sustainablefashion', '#ethicalfashion', '#slowfashion'],
    min_score_threshold: 50,
    profiles_discovered: 0,
    profiles_scored: 0,
    created_at: hoursAgo(0.2),
    updated_at: hoursAgo(0.2),
  },
]
